spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

app:
  cookie:
    secure: false
  jwt:
    secret: ${JWT_SECRET}
